/**
 * Texte des Panels, Deutsch und Englisch. Jeder Schlüssel muss in beiden
 * Sprachen vorhanden sein (tests/panel prüft das). Funktionen statt Strings
 * dort, wo Zahlen oder Namen eingesetzt werden.
 */

export const STRINGS = {
  de: {
    searchPlaceholder: "In allen Spalten suchen…",
    filterPlaceholder: "Filter…",
    ipPlaceholder: "z.B. 192.168.1.",
    optAll: "Alle",
    seen1h: "< 1 Std.",
    seen24h: "< 24 Std.",
    seen7d: "> 7 Tage",
    activeFilters: "Aktive Filter:",
    clearAll: "Alle entfernen",
    filtersTitle: "Spaltenfilter",
    columnsBtn: "Spalten",
    columnsTitle: "Spalten anzeigen",
    columnsAll: "Alle einblenden",
    columnsDefault: "Standard",
    columnsDrag: (label) => `${label} verschieben (ziehen oder Pfeiltasten)`,
    showN: (n, total) => `${n} von ${total} Clients anzeigen`,
    footer: (n, total, time) => `${n} von ${total} Clients angezeigt · Stand ${time}`,
    footerHint: "Zeile antippen für Details",
    protectedTitle: "Vor automatischem Löschen geschützt",
    statsGroup: "Status-Filter",
    statTotal: (n) => (n === 1 ? "Gerät" : "Geräte"),
    statOnline: "online",
    statOffline: "offline",
    statShowAll: "Alle anzeigen",
    statShowOnline: "Nur Online-Geräte anzeigen",
    statShowOffline: "Nur Offline-Geräte anzeigen",
    colName: "Alias",
    colLinked: "HA-Gerät",
    colIp: "IP",
    colMac: "MAC",
    colSsid: "SSID",
    colAp: "Access Point",
    colConn: "Verbindung",
    colSeen: "Zuletzt gesehen",
    colStatus: "Status",
    colActions: "",
    statusOnline: "Online",
    statusOffline: "Offline",
    connWired: "Kabel",
    connWireless: "WLAN",
    connUnknown: "unbekannt",
    excludedBadge: "geschützt",
    menuDetails: "Details",
    menuOpenDevice: "HA-Geräteseite öffnen",
    menuExclude: "Vor automatischem Löschen schützen",
    menuUnexclude: "Nicht mehr schützen",
    menuRemove: "Löschen",
    confirmRemove: (name) =>
      `${name} jetzt entfernen? Ist der Client noch aktiv, wird er beim nächsten Abgleich neu angelegt.`,
    empty: "Keine Clients gefunden.",
    loading: "Lädt…",
    error: "Fehler beim Laden der Clientliste:",
    errorConnection: "Keine Verbindung zu Home Assistant. Es wird automatisch erneut versucht.",
    errorCode: "Fehlercode",
    retry: "Erneut versuchen",
    resetFilters: "Filter zurücksetzen",
    clearSearch: "Suche leeren",
    seenNever: "–",
    dialogClose: "Schliessen",
    fieldConn: "Verbindung",
    fieldIp: "IP-Adresse",
    fieldMac: "MAC-Adresse",
    fieldHostname: "Hostname",
    fieldSsid: "SSID",
    fieldAp: "Access Point",
    fieldSignal: "Signal (RSSI)",
    fieldFirstSeen: "Zuerst gesehen",
    fieldLastSeen: "Zuletzt gesehen",
    fieldHost: "UniFi-Host",
    signalLast: "zuletzt gemessen",
    unknown: "unbekannt",
    secEntities: "Entitäten",
    entitiesNone: "Keine Entitäten.",
    entitiesNoDevice: "Home Assistant hat für diesen Client noch kein Gerät angelegt.",
    notFound: "Dieser Client ist nicht (mehr) vorhanden.",
    actionFailed: "Aktion fehlgeschlagen:",
    copy: (what) => `${what} kopieren`,
    copied: (value) => `Kopiert: ${value}`,
    copyFailed: "Kopieren nicht möglich - der Browser erlaubt keinen Zugriff auf die Zwischenablage.",
    secLinked: "Verknüpftes Gerät",
    secNetwork: "Netzwerk",
    hubAll: "Alle Hubs",
    hubSelect: "Hub wählen",
    settingsBtn: "Einstellungen",
    settingsNeedHub: "Einstellungen gelten pro Hub – zuerst einen Hub wählen",
    settingsTitle: "Einstellungen",
    secConnection: "Verbindung",
    connHost: "Host / IP",
    connSite: "Site",
    connSsl: "SSL-Zertifikat prüfen",
    connKey: "API-Key",
    connKeyStored: "hinterlegt",
    connKeyMissing: "fehlt",
    connYes: "ja",
    connNo: "nein",
    connStatus: "Status",
    connOk: "Verbunden",
    connAuthFailed: "API-Key ungültig",
    connOffline: "Nicht erreichbar",
    connEdit: "Verbindung ändern…",
    connRenew: "API-Key erneuern",
    connBanner: "Der Controller lehnt den hinterlegten API-Key ab. Es werden keine Clients mehr aktualisiert.",
    connDlgTitle: "Verbindung ändern",
    connNewKey: "Neuer API-Key",
    connNewKeyHint: "Leer lassen, um den hinterlegten Key zu behalten.",
    connNewKeyRequired: "Bitte den neuen API-Key eingeben.",
    connHint: "Die Verbindung wird vor dem Speichern getestet. Danach wird die Integration neu geladen; Geräte, Entitäten, Verknüpfungen und Einstellungen bleiben erhalten.",
    connTest: "Testen und speichern",
    connTesting: "Verbindung wird getestet…",
    connSaved: "Verbindung gespeichert, Integration wird neu geladen",
    connErr_invalid_auth: "API-Key ungültig. Der Controller lehnt den Key ab.",
    connErr_cannot_connect: "Host nicht erreichbar. Adresse und SSL-Einstellung prüfen.",
    connErr_invalid_host: "Bitte Host oder IP angeben.",
    connErr_already_configured: "Dieser Host mit dieser Site wird bereits von einem anderen Hub verwendet.",
    connErr_site_not_found:
      "Die Site dieses Hubs gibt es auf dem neuen Host nicht. Site wechseln: Einstellungen → Geräte & Dienste → UniFi Dynamic Clients → Neu konfigurieren.",
    connErr_other: "Speichern fehlgeschlagen:",
    settingsLoading: "Einstellungen werden geladen…",
    settingsLoadError: "Einstellungen konnten nicht geladen werden:",
    settingsSaveError: "Speichern fehlgeschlagen:",
    settingsChanged: "geändert",
    settingsChanges: (n) => (n === 1 ? "1 Änderung" : `${n} Änderungen`),
    settingsReloadNote:
      "Beim Speichern lädt die Integration kurz neu (Abfrageintervall oder Uhrzeit geändert). Die Entitäten sind 1–2 Sekunden nicht verfügbar.",
    settingsCancel: "Abbrechen",
    settingsSave: "Speichern",
    settingsSaving: "Speichert…",
    settingsSaved: "Einstellungen gespeichert.",
    settingsSavedReload: "Einstellungen gespeichert – die Integration lädt kurz neu.",
    settingsInfo: "Mehr erfahren",
    settingsRange: (min, max) => `Erlaubt: ${min}–${max}`,
    settingsTimeError: "Uhrzeit im Format HH:MM",
    secPolling: "Abfrage",
    secCleanup: "Automatisches Entfernen",
    secPush: "Push-Benachrichtigung",
    secPersistent: "Anhaltende Benachrichtigung",
    secPing: "Ping (Antwortzeit)",
    sumPingOff: "Aus",
    sumPingBlocked: "Eingeschaltet, aber Ping ist nicht erlaubt",
    sumPingOn: (sec) => `Alle ${sec} s · Median, Schwankung, Paketverlust`,
    optPingEnabled: "Antwortzeit messen",
    optPingEnabledShort: "Pingt alle Online-Clients über ihre aktuelle IP aus UniFi.",
    optPingEnabledInfo:
      "Schickt pro Runde drei Pings an jeden Client, der laut UniFi online ist, und hält Median, Schwankung und Paketverlust 24 Stunden lang fest. Die Werte stehen in der Geräteansicht und in der Spalte „Ping“; Dazu legt die Integration für jeden Client die Sensoren „Ping“ und „Packet loss“ an. Viele Geräte antworten grundsätzlich nicht auf Ping (Windows-Firewall, Handys im Standby, IoT-Geräte, Firewall zwischen VLANs) – sie erscheinen als „antwortet nicht auf Ping“, das ist kein Fehler. Ein- und Ausschalten lädt die Integration kurz neu.",
    optPingInterval: "Intervall",
    optPingIntervalShort: "Abstand zwischen zwei Runden. 60 s sind ein guter Kompromiss.",
    pingPermission:
      "Home Assistant darf keine Ping-Pakete (ICMP) senden, die Messung ist deshalb aus. In Home Assistant OS funktioniert Ping; bei Docker- oder Core-Installationen muss unprivilegierter Ping erlaubt sein (net.ipv4.ping_group_range) oder Home Assistant mit Root-Rechten laufen.",
    pingUnavailable: "Die Ping-Bibliothek (icmplib) fehlt. Nach einem Neustart von Home Assistant wird sie installiert.",
    colPing: "Ping",
    pingNoReplyShort: "keine Antwort",
    pingLossShort: (p) => `${p} % Verlust`,
    pingTierNames: ["", "schlecht", "langsam", "ok", "gut", "sehr gut"],
    pingTitle: "Antwortzeit",
    pingRange: { "24h": "Letzte 24 Std.", "7d": "Letzte 7 Tage", "30d": "Letzte 30 Tage" },
    pingMedian: "Median",
    pingJitter: "Schwankung",
    pingLoss: "Paketverlust",
    pingNoData: "Noch keine Messwerte – der Client wird gepingt, sobald er online ist und eine IP hat.",
    pingNoReply:
      "Antwortet nicht auf Ping. Das ist bei vielen Geräten normal (Windows-Firewall, Handys im Standby, IoT-Geräte, Firewall zwischen VLANs) und kein Fehler.",
    pingAgo: { "24h": "vor 24 Std.", "7d": "vor 7 Tagen", "30d": "vor 30 Tagen" },
    pingScale: (ms) => `bis ${ms} ms`,
    pingBarTip: (time, ms, loss) => `${time} · ${ms} · ${loss}`,
    pingEntityNote: "Auch als Sensoren „Ping“ (ms) und „Packet loss“ (%) am Gerät, für Automationen und den Verlauf in Home Assistant.",
    secUpdates: "Updates",
    sumUpdatesOn: "Tägliche Prüfung auf neue Versionen",
    sumUpdatesOff: "Keine automatische Prüfung",
    optUpdateCheck: "Täglich nach Updates suchen",
    optUpdateCheckShort: "Meldet eine neue Version unter Einstellungen → Reparaturen.",
    optUpdateCheckInfo:
      "Fragt einmal täglich die veröffentlichten Releases auf GitHub ab, die erste Prüfung zufällig 5–65 Minuten nach dem Start. Ergänzt HACS, das nur alle paar Tage prüft; wer die doppelte Meldung nicht möchte, schaltet es aus. Gilt für die ganze Integration, solange es bei mindestens einem Hub eingeschaltet ist.",
    sumPolling: (i, n) => `Alle ${i} s · ausgefallen nach ${n} Abfragen`,
    sumCleanup: (d, time) => (d ? `Nach ${d} Tagen ohne Sichtung · täglich ${time}` : "Ausgeschaltet"),
    sumPushOff: "Keine Push-Benachrichtigung",
    sumPersistentOff: "Ausgeschaltet",
    sumNew: "neue Geräte",
    sumController: "Controller-Ausfall",
    sumEmpty: "auch ohne Treffer",
    sumReport: "Bericht des Aufräumlaufs",
    unitSeconds: "s",
    unitPolls: "Abfragen",
    unitDays: "Tagen",
    optScanInterval: "Abfrageintervall",
    optScanIntervalShort: "Wie oft die Clientliste geholt wird (10–3600 s).",
    optScanIntervalInfo:
      "Kürzere Intervalle erkennen Wechsel schneller, belasten den Controller aber stärker. Änderungen laden die Integration kurz neu.",
    optOfflineAfter: "Als ausgefallen nach",
    optOfflineAfterLive: (i, dur) => `Bei ${i} s Intervall: nach ${dur}`,
    optOfflineAfterInfo:
      "Zählt fehlgeschlagene Abfragen in Folge. Niedrige Werte melden schneller, reagieren aber auch auf einzelne Aussetzer. Die Entwarnung kommt mit der ersten erfolgreichen Abfrage.",
    optPurgeDays: "Entfernen nach",
    optPurgeDaysShort: "Tage ohne Sichtung, 0 schaltet es aus.",
    optPurgeDaysInfo:
      "Wer länger nicht gesehen wurde, verliert beim täglichen Lauf seine Entitäten und sein Gerät in Home Assistant. Geschützte Clients sind ausgenommen.",
    optPurgeTime: "Uhrzeit des täglichen Laufs",
    optPurgeTimeShort: "Lokale Zeit.",
    optPurgeTimeInfo:
      "Zusätzlich läuft eine Prüfung 60 Sekunden nach jedem Start von Home Assistant; sie meldet nur, wenn etwas entfernt wurde. Manuell auslösbar über die Aktion unifi_dynamic.purge_now, auch als Testlauf. Änderungen laden die Integration kurz neu.",
    optProtected: "Geschützte Clients",
    optProtectedShort: "Werden nie automatisch entfernt.",
    optProtectedInfo: "Hinzufügen über \"Schützen\" in der Tabelle oder in der Geräteansicht.",
    optProtectedNone: "Keine geschützten Clients.",
    optProtectedUnknown: "nicht mehr bekannt",
    optUnprotect: (name) => `Schutz für ${name} aufheben`,
    optNotifyService: "Ziel",
    optNotifyServiceShort: "notify-Dienst oder -Entität.",
    optNotifyServiceInfo: "Zum Beispiel eine notify-Gruppe, um mehrere Handys zu erreichen.",
    optNotifyNone: "Keine Push-Benachrichtigung",
    optNotifyMissing: "nicht gefunden",
    optClickTarget: "Tipp auf Gerätemeldung öffnet",
    optClickTargetShort: "Wohin die Meldung zu einem Client führt.",
    optClickTargetInfo:
      "\"Geräteansicht im Panel\" zeigt Details und Aktionen, auch ohne HA-Gerät. \"HA-Geräteseite\" ist für alle ohne Panel gedacht. Sammel- und Controller-Meldungen öffnen immer die Integrationsseite.",
    optClickPanel: "Geräteansicht im Panel",
    optClickDevice: "HA-Geräteseite",
    optNotifyNew: "Neue Geräte melden",
    optNotifyNewShort: "Sobald ein Client zum ersten Mal auftaucht.",
    optNotifyNewInfo:
      "Wartet bis zu 120 Sekunden, bis IP, SSID und Access Point bekannt sind. Ab 6 Clients gleichzeitig kommt eine Sammelmeldung. Nach der Installation wird bewusst nichts gemeldet.",
    optNotifyController: "Controller-Ausfall melden",
    optNotifyControllerShort: "Einmal je Störung, mit Entwarnung.",
    optNotifyControllerInfo:
      "Ab wann der Controller als ausgefallen gilt, legt \"Als ausgefallen nach\" fest. Während der Störung werden keine Clients aktualisiert.",
    optNotifyEmpty: "Auch ohne Treffer melden",
    optNotifyEmptyShort: "Push nach jedem täglichen Lauf.",
    optContent: "Inhalt der Meldung",
    optContentShort: "Welche Angaben in der Meldung über neue Geräte stehen.",
    optContentInfo:
      "Ist alles aus, wird der Anzeigename gemeldet. SSID und Access Point gibt es nur bei WLAN-Clients. Die MAC wird weggelassen, wenn sie schon der Name ist.",
    msgName: "Anzeigename",
    msgConnection: "Verbindungsart",
    msgSsid: "SSID",
    msgAp: "Access Point",
    msgIp: "IP-Adresse",
    msgMac: "MAC-Adresse",
    optPersistent: "Anhaltende Benachrichtigung",
    optPersistentShort: "Bericht des Aufräumlaufs in der Seitenleiste.",
    optPersistentInfo: "Neu erkannte Geräte erzeugen nie eine anhaltende Benachrichtigung.",
    optPersistentEmpty: "Auch ohne Treffer",
    optPersistentEmptyShort: "Sonst nur, wenn etwas entfernt wurde.",
    optPersistentEmptyInfo: "Aus heisst: Die letzte Meldung bleibt stehen und zeigt den letzten echten Lauf.",
    optPersistentController: "Controller-Ausfall",
    optPersistentControllerShort: "Solange der Controller nicht antwortet.",
    optPersistentControllerInfo: "Verschwindet automatisch, sobald er wieder erreichbar ist.",
    statTitle: "Statistik · 24 Std.",
    statCtlTitle: "Controller · 24 Std.",
    statNoData: "Noch keine Daten",
    statNoOutages: "Keine Unterbrüche",
    statOutages: (n, longest) => `${n} ${n === 1 ? "Unterbruch" : "Unterbrüche"} · längster ${longest}`,
    tileAvail: "Verfügbarkeit",
    tileWifi: "WLAN-Empfang",
    tileWifiShort: "WLAN",
    tilePing: "Antwortzeit",
    // Tabs im Statistik-Fenster: [lang, kurz (Handy)]
    statTabs: { avail: ["Verfügbarkeit", "Verfügbar"], wifi: ["WLAN", "WLAN"], ping: ["Antwortzeit", "Ping"] },
    tilePingSilent: "Kein Fehler",
    wifiTierNames: ["", "schlecht", "schwach", "ok", "sehr gut"],
    wifiMedian: "Median",
    wifiBest: "Bester",
    wifiWorst: "Schlechtester",
    wifiAps: "Access Points",
    wifiGaps: "Ohne WLAN-Daten",
    wifiGapsNone: "keine Lücken",
    wifiNoData: "Noch keine WLAN-Daten. Der Verlauf wird seit dem Update auf 2.15.0 bei jeder Abfrage aufgezeichnet.",
    wifiLegend: ["", "unter −75 dBm", "−75 … −68", "−67 … −61", "ab −60 dBm"],
    secAvail: "Verfügbarkeit",
    secCtlAvail: "Controller-Verfügbarkeit",
    verName: (v) => `UniFi Dynamic Clients ${v}`,
    verCurrent: "Aktuell",
    verChecked: (rel) => `zuletzt geprüft ${rel}`,
    verCheck: "Nach Updates suchen",
    verChecking: "Prüft…",
    verCheckingSub: "Suche nach Updates…",
    verCheckError: "Prüfung fehlgeschlagen:",
    verAvailable: (v) => `Version ${v} verfügbar`,
    verBeta: "Beta",
    verInstalled: (v) => `Installiert: ${v}`,
    verPreShort: "Vorabversion",
    verPreToggle: "Vorabversionen anzeigen",
    verPreToggleShort: "Auch Beta-Versionen zum Testen anbieten. Gilt für alle Benutzer.",
    verPreHint:
      "HACS installiert Vorabversionen nur, wenn bei dieser Integration „Pre-release“ eingeschaltet ist: im HACS-Gerät die Entität „Pre-release“ aktivieren und einschalten.",
    verPreHintLink: "HACS-Gerät öffnen",
    verPreHintEnable:
      "HACS installiert Vorabversionen nur, wenn bei dieser Integration „Pre-release“ eingeschaltet ist. Das Panel kann das für dich erledigen: Es aktiviert die Entität in HACS und schaltet sie ein. HACS lädt dabei kurz neu (etwa 30 Sekunden). Schaltest du „Vorabversionen anzeigen“ später aus, wird sie wieder ausgeschaltet.",
    verPreEnable: "In HACS freischalten",
    verPreEnabling: "Wird freigeschaltet … (bis 30 s)",
    verPreEnableError: "Freischalten fehlgeschlagen:",
    verPreEnableTimeout: "HACS hat die Entität nicht rechtzeitig bereitgestellt. Bitte im HACS-Gerät prüfen.",
    verInstalledVia: (v, hacs) => `Installiert: ${v}${hacs ? " · über HACS" : ""}`,
    verNoHacs: "Installation über HACS oder manuell (siehe Release Notes).",
    verReleaseNotes: "Release Notes",
    verUpdate: "Aktualisieren",
    verInstalling: (v) => `Wird aktualisiert auf ${v}…`,
    verInstallingSub: "HACS lädt die neue Version herunter",
    verInstallError: "Aktualisieren fehlgeschlagen:",
    verHacsSyncing: "Wird mit HACS abgeglichen …",
    verHacsPending:
      "HACS kennt diese Version noch nicht. \"Nach Updates suchen\" lässt HACS die Versionen neu laden; sonst später erneut versuchen.",
    verRestartNeeded: (v) => `${v} installiert – Neustart nötig`,
    verRestartSub: "Aktiv wird die neue Version erst nach einem Neustart von Home Assistant.",
    verRestart: "Jetzt neu starten",
    verRestartConfirm: "Home Assistant jetzt neu starten? Alle Integrationen sind dabei kurz nicht verfügbar.",
    verRestarting: "Home Assistant startet neu…",
    availCtlNoData: "Noch keine Daten – die Aufzeichnung läuft seit dem Update auf 2.9.0.",
    availRanges: { "24h": "24 Std.", "7d": "7 Tage", "30d": "30 Tage" },
    availRangeGroup: "Zeitraum",
    availLoading: "Verlauf wird geladen…",
    loaderTitle: "Loader",
    loaderShort: "Lade-Animation, während der Verlauf geladen wird. Gilt nur für dich, auf allen Geräten.",
    settingsSaveHint: "„Speichern“ gilt für Abfrage, Automatisches Entfernen, Benachrichtigungen, Updates und Ping. Loader und Verbindung werden direkt übernommen.",
    loaderNames: {
      elephant: ["Elefant", "Balance auf dem Ball"],
      cat: ["Katze", "Anschleichen und Anspringen"],
      hamster: ["Hamster", "Im Laufrad"],
      penguin: ["Pinguin", "…und der Eisbär"],
      runner: ["Laufvogel", "…und der Kojote"],
      random: ["Zufall", "Jedes Mal eine andere"],
    },
    loaderSelect: (name) => `Loader ${name} wählen`,
    loaderWords: {
      cat: ["Schleicht sich an die Daten an…", "Hintern wackelt. Gleich…", "Sprung! Knapp daneben.", "Tut so, als wäre nichts gewesen."],
      hamster: ["Rennt, so schnell er kann…", "Das Rad dreht, die Daten kommen.", "Keine Pause. Keine Ahnung wohin.", "Gleich drüben…"],
      penguin: ["Watschelt durch den Verlauf…", "Da kommt wer! Abtauchen!", "Der Bär wundert sich noch.", "Taucht mit den Daten wieder auf…"],
      runner: ["Flitzt durch den Verlauf…", "Der Tunnel ist nur aufgemalt. Für manche.", "Aua.", "Mip mip! Daten sind unterwegs…"],
    },
    availLoadingWords: [
      "Balanciert durch den Verlauf…",
      "Wackelt. Fällt nicht. Wie der Controller.",
      "Ein Elefant vergisst nichts, er rollt nur langsam.",
      "Gleich drüben…",
    ],
    availError: "Verlauf nicht verfügbar:",
    availNoEntity: "Keine Online-Entität gefunden - ohne HA-Gerät gibt es keinen Verlauf.",
    availNoData: "Keine Verlaufsdaten im Recorder für diesen Zeitraum.",
    availAlways: "Durchgehend erreichbar",
    availNever: "Im ganzen Zeitraum nicht erreichbar",
    availOutages: (n) => (n === 1 ? "1 Unterbruch" : `${n} Unterbrüche`),
    availTotal: (d) => `zusammen ${d}`,
    availLongest: (d) => `längster ${d}`,
    availSince: (time) => `erst seit ${time} Daten`,
    availOnline: "Erreichbar",
    availOffline: "Unterbruch",
    availNone: "Keine Daten",
    availNow: "jetzt",
    availOngoing: "läuft",
    availMore: (n) => `${n} ältere Unterbrüche nicht aufgelistet.`,
    availTip: "Offline",
    durMin: (n) => `${n} Min.`,
    durHour: (h, m) => (m ? `${h} Std. ${m} Min.` : `${h} Std.`),
    durDay: (d, h) => (h ? `${d} T. ${h} Std.` : `${d} T.`),
    quickProtect: "Schützen",
    quickUnprotect: "Schutz aufheben",
    linkedNone: "Kein Home-Assistant-Gerät verknüpft.",
    linkAdd: "Gerät verknüpfen…",
    linkChange: "Ändern",
    linkRemove: "Verknüpfung entfernen",
    linkCancel: "Abbrechen",
    linkOpen: (name) => `Geräteseite von ${name} öffnen`,
    pickerSearch: "Gerät suchen (Name, Bereich, Hersteller)…",
    pickerSuggested: "Passt zur MAC-Adresse",
    pickerAll: "Alle Geräte",
    pickerNone: "Kein Gerät gefunden.",
    pickerMore: (n) => `${n} weitere - Suche verfeinern.`,
    pickerCurrent: "verknüpft",
    pickerHideLinked: "Bereits verknüpfte ausblenden",
    pickerLinkedTo: (names) => `Bereits verknüpft mit: ${names}`,
    pickerHiddenCount: (n) =>
      n === 1 ? "1 bereits verknüpftes Gerät ausgeblendet." : `${n} bereits verknüpfte Geräte ausgeblendet.`,
  },
  en: {
    searchPlaceholder: "Search all columns…",
    filterPlaceholder: "Filter…",
    ipPlaceholder: "e.g. 192.168.1.",
    optAll: "All",
    seen1h: "< 1 h",
    seen24h: "< 24 h",
    seen7d: "> 7 days",
    activeFilters: "Active filters:",
    clearAll: "Clear all",
    filtersTitle: "Column filters",
    columnsBtn: "Columns",
    columnsTitle: "Show columns",
    columnsAll: "Show all",
    columnsDefault: "Default",
    columnsDrag: (label) => `Move ${label} (drag or arrow keys)`,
    showN: (n, total) => `Show ${n} of ${total} clients`,
    footer: (n, total, time) => `${n} of ${total} clients shown · as of ${time}`,
    footerHint: "Tap a row for details",
    protectedTitle: "Protected from automatic removal",
    statsGroup: "Status filter",
    statTotal: (n) => (n === 1 ? "device" : "devices"),
    statOnline: "online",
    statOffline: "offline",
    statShowAll: "Show all",
    statShowOnline: "Show online devices only",
    statShowOffline: "Show offline devices only",
    colName: "Alias",
    colLinked: "HA device",
    colIp: "IP",
    colMac: "MAC",
    colSsid: "SSID",
    colAp: "Access point",
    colConn: "Connection",
    colSeen: "Last seen",
    colStatus: "Status",
    colActions: "",
    statusOnline: "Online",
    statusOffline: "Offline",
    connWired: "Wired",
    connWireless: "Wireless",
    connUnknown: "unknown",
    excludedBadge: "protected",
    menuDetails: "Details",
    menuOpenDevice: "Open HA device page",
    menuExclude: "Protect from automatic removal",
    menuUnexclude: "Stop protecting",
    menuRemove: "Remove",
    confirmRemove: (name) =>
      `Remove ${name} now? If the client is still active, it will be recreated on the next sync.`,
    empty: "No clients found.",
    loading: "Loading…",
    error: "Failed to load the client list:",
    errorConnection: "No connection to Home Assistant. Retrying automatically.",
    errorCode: "Error code",
    retry: "Retry",
    resetFilters: "Reset filters",
    clearSearch: "Clear search",
    seenNever: "–",
    dialogClose: "Close",
    fieldConn: "Connection",
    fieldIp: "IP address",
    fieldMac: "MAC address",
    fieldHostname: "Hostname",
    fieldSsid: "SSID",
    fieldAp: "Access point",
    fieldSignal: "Signal (RSSI)",
    fieldFirstSeen: "First seen",
    fieldLastSeen: "Last seen",
    fieldHost: "UniFi host",
    signalLast: "last measured",
    unknown: "unknown",
    secEntities: "Entities",
    entitiesNone: "No entities.",
    entitiesNoDevice: "Home Assistant has not created a device for this client yet.",
    notFound: "This client does not exist (anymore).",
    actionFailed: "Action failed:",
    copy: (what) => `Copy ${what}`,
    copied: (value) => `Copied: ${value}`,
    copyFailed: "Could not copy - the browser does not allow access to the clipboard.",
    secLinked: "Linked device",
    secNetwork: "Network",
    hubAll: "All hubs",
    hubSelect: "Choose hub",
    settingsBtn: "Settings",
    settingsNeedHub: "Settings apply per hub – choose a hub first",
    settingsTitle: "Settings",
    secConnection: "Connection",
    connHost: "Host / IP",
    connSite: "Site",
    connSsl: "Verify SSL certificate",
    connKey: "API key",
    connKeyStored: "stored",
    connKeyMissing: "missing",
    connYes: "yes",
    connNo: "no",
    connStatus: "Status",
    connOk: "Connected",
    connAuthFailed: "API key invalid",
    connOffline: "Not reachable",
    connEdit: "Change connection…",
    connRenew: "Renew API key",
    connBanner: "The controller rejects the stored API key. Clients are no longer updated.",
    connDlgTitle: "Change connection",
    connNewKey: "New API key",
    connNewKeyHint: "Leave empty to keep the stored key.",
    connNewKeyRequired: "Please enter the new API key.",
    connHint: "The connection is tested before saving. The integration then reloads; devices, entities, links and settings are kept.",
    connTest: "Test and save",
    connTesting: "Testing connection…",
    connSaved: "Connection saved, integration is reloading",
    connErr_invalid_auth: "API key invalid. The controller rejects the key.",
    connErr_cannot_connect: "Host not reachable. Check address and SSL setting.",
    connErr_invalid_host: "Please enter a host or IP.",
    connErr_already_configured: "This host and site are already used by another hub.",
    connErr_site_not_found:
      "This hub's site does not exist on the new host. To change the site: Settings → Devices & services → UniFi Dynamic Clients → Reconfigure.",
    connErr_other: "Saving failed:",
    settingsLoading: "Loading settings…",
    settingsLoadError: "Could not load the settings:",
    settingsSaveError: "Saving failed:",
    settingsChanged: "changed",
    settingsChanges: (n) => (n === 1 ? "1 change" : `${n} changes`),
    settingsReloadNote:
      "Saving briefly reloads the integration (update interval or time changed). The entities are unavailable for 1–2 seconds.",
    settingsCancel: "Cancel",
    settingsSave: "Save",
    settingsSaving: "Saving…",
    settingsSaved: "Settings saved.",
    settingsSavedReload: "Settings saved – the integration is reloading.",
    settingsInfo: "Learn more",
    settingsRange: (min, max) => `Allowed: ${min}–${max}`,
    settingsTimeError: "Time as HH:MM",
    secPolling: "Polling",
    secCleanup: "Automatic removal",
    secPush: "Push notification",
    secPersistent: "Persistent notification",
    secPing: "Ping (response time)",
    sumPingOff: "Off",
    sumPingBlocked: "On, but ping is not permitted",
    sumPingOn: (sec) => `Every ${sec} s · median, jitter, packet loss`,
    optPingEnabled: "Measure response time",
    optPingEnabledShort: "Pings all online clients at their current IP from UniFi.",
    optPingEnabledInfo:
      "Sends three pings per round to every client that UniFi reports online and keeps median, jitter and packet loss for 24 hours. The values appear in the device view and in the \"Ping\" column; \"Ping\" and \"Packet loss\" sensors are created for every client. Many devices never answer ping (Windows firewall, phones in standby, IoT devices, firewalls between VLANs) – they show up as \"does not answer ping\", which is not an error. Switching it on or off briefly reloads the integration.",
    optPingInterval: "Interval",
    optPingIntervalShort: "Time between two rounds. 60 s is a good compromise.",
    pingPermission:
      "Home Assistant is not allowed to send ping (ICMP) packets, so measuring is off. Ping works on Home Assistant OS; on Docker or Core installations unprivileged ping must be allowed (net.ipv4.ping_group_range) or Home Assistant must run as root.",
    pingUnavailable: "The ping library (icmplib) is missing. It is installed after restarting Home Assistant.",
    colPing: "Ping",
    pingNoReplyShort: "no reply",
    pingLossShort: (p) => `${p} % loss`,
    pingTierNames: ["", "poor", "slow", "fair", "good", "very good"],
    pingTitle: "Response time",
    pingRange: { "24h": "Last 24 h", "7d": "Last 7 days", "30d": "Last 30 days" },
    pingMedian: "Median",
    pingJitter: "Jitter",
    pingLoss: "Packet loss",
    pingNoData: "No measurements yet – the client is pinged as soon as it is online and has an IP.",
    pingNoReply:
      "Does not answer ping. That is normal for many devices (Windows firewall, phones in standby, IoT devices, firewalls between VLANs) and not an error.",
    pingAgo: { "24h": "24 h ago", "7d": "7 days ago", "30d": "30 days ago" },
    pingScale: (ms) => `up to ${ms} ms`,
    pingBarTip: (time, ms, loss) => `${time} · ${ms} · ${loss}`,
    pingEntityNote: "Also available as \"Ping\" (ms) and \"Packet loss\" (%) sensors on the device, for automations and history in Home Assistant.",
    secUpdates: "Updates",
    sumUpdatesOn: "Daily check for new versions",
    sumUpdatesOff: "No automatic check",
    optUpdateCheck: "Check for updates daily",
    optUpdateCheckShort: "Reports a new version under Settings → Repairs.",
    optUpdateCheckInfo:
      "Queries the published releases on GitHub once a day, the first check at a random time 5–65 minutes after startup. Complements HACS, which only checks every few days; turn it off if you don't want the duplicate notice. Applies to the whole integration as long as it is on for at least one hub.",
    sumPolling: (i, n) => `Every ${i} s · offline after ${n} polls`,
    sumCleanup: (d, time) => (d ? `After ${d} days unseen · daily at ${time}` : "Off"),
    sumPushOff: "No push notification",
    sumPersistentOff: "Off",
    sumNew: "new devices",
    sumController: "controller outage",
    sumEmpty: "also without hits",
    sumReport: "Cleanup report",
    unitSeconds: "s",
    unitPolls: "polls",
    unitDays: "days",
    optScanInterval: "Update interval",
    optScanIntervalShort: "How often the client list is fetched (10–3600 s).",
    optScanIntervalInfo:
      "Shorter intervals detect changes faster but put more load on the controller. Changes briefly reload the integration.",
    optOfflineAfter: "Offline after",
    optOfflineAfterLive: (i, dur) => `At a ${i} s interval: after ${dur}`,
    optOfflineAfterInfo:
      "Counts failed polls in a row. Low values report faster but also react to single hiccups. The all-clear comes with the first successful poll.",
    optPurgeDays: "Remove after",
    optPurgeDaysShort: "Days unseen, 0 turns it off.",
    optPurgeDaysInfo:
      "Clients unseen for longer lose their entities and device in Home Assistant during the daily run. Protected clients are exempt.",
    optPurgeTime: "Time of the daily run",
    optPurgeTimeShort: "Local time.",
    optPurgeTimeInfo:
      "In addition, a check runs 60 seconds after every Home Assistant start; it only reports when something was removed. Can be triggered manually with the unifi_dynamic.purge_now action, also as a dry run. Changes briefly reload the integration.",
    optProtected: "Protected clients",
    optProtectedShort: "Never removed automatically.",
    optProtectedInfo: "Add clients with \"Protect\" in the table or in the device view.",
    optProtectedNone: "No protected clients.",
    optProtectedUnknown: "no longer known",
    optUnprotect: (name) => `Stop protecting ${name}`,
    optNotifyService: "Target",
    optNotifyServiceShort: "notify service or entity.",
    optNotifyServiceInfo: "For example a notify group to reach several phones.",
    optNotifyNone: "No push notification",
    optNotifyMissing: "not found",
    optClickTarget: "Tapping a device notification opens",
    optClickTargetShort: "Where the notification about a client leads.",
    optClickTargetInfo:
      "\"Device view in the panel\" shows details and actions, even without a HA device. \"HA device page\" is for anyone not using the panel. Summary and controller notifications always open the integration page.",
    optClickPanel: "Device view in the panel",
    optClickDevice: "HA device page",
    optNotifyNew: "Report new devices",
    optNotifyNewShort: "As soon as a client appears for the first time.",
    optNotifyNewInfo:
      "Waits up to 120 seconds until IP, SSID and access point are known. From 6 clients at once a summary is sent. Nothing is reported right after installation.",
    optNotifyController: "Report controller outage",
    optNotifyControllerShort: "Once per outage, with all-clear.",
    optNotifyControllerInfo:
      "When the controller counts as down is set by \"Offline after\". During the outage no clients are updated.",
    optNotifyEmpty: "Also report without hits",
    optNotifyEmptyShort: "Push after every daily run.",
    optContent: "Notification content",
    optContentShort: "Which details the notification about new devices contains.",
    optContentInfo:
      "If everything is off, the display name is sent. SSID and access point only exist for wireless clients. The MAC is left out when it already is the name.",
    msgName: "Display name",
    msgConnection: "Connection type",
    msgSsid: "SSID",
    msgAp: "Access point",
    msgIp: "IP address",
    msgMac: "MAC address",
    optPersistent: "Persistent notification",
    optPersistentShort: "Cleanup report in the sidebar.",
    optPersistentInfo: "Newly detected devices never create a persistent notification.",
    optPersistentEmpty: "Also without hits",
    optPersistentEmptyShort: "Otherwise only when something was removed.",
    optPersistentEmptyInfo: "Off means: the last notification stays and shows the last real run.",
    optPersistentController: "Controller outage",
    optPersistentControllerShort: "While the controller doesn't respond.",
    optPersistentControllerInfo: "Disappears automatically once it is reachable again.",
    statTitle: "Statistics · 24 h",
    statCtlTitle: "Controller · 24 h",
    statNoData: "No data yet",
    statNoOutages: "No outages",
    statOutages: (n, longest) => `${n} ${n === 1 ? "outage" : "outages"} · longest ${longest}`,
    tileAvail: "Availability",
    tileWifi: "WiFi signal",
    tileWifiShort: "WiFi",
    tilePing: "Response time",
    statTabs: { avail: ["Availability", "Uptime"], wifi: ["WiFi", "WiFi"], ping: ["Response time", "Ping"] },
    tilePingSilent: "Not an error",
    wifiTierNames: ["", "poor", "weak", "fair", "very good"],
    wifiMedian: "Median",
    wifiBest: "Best",
    wifiWorst: "Worst",
    wifiAps: "Access points",
    wifiGaps: "Without WiFi data",
    wifiGapsNone: "no gaps",
    wifiNoData: "No WiFi data yet. The history is recorded on every poll since updating to 2.15.0.",
    wifiLegend: ["", "below −75 dBm", "−75 … −68", "−67 … −61", "from −60 dBm"],
    secAvail: "Availability",
    secCtlAvail: "Controller availability",
    verName: (v) => `UniFi Dynamic Clients ${v}`,
    verCurrent: "Up to date",
    verChecked: (rel) => `last checked ${rel}`,
    verCheck: "Check for updates",
    verChecking: "Checking…",
    verCheckingSub: "Looking for updates…",
    verCheckError: "Check failed:",
    verAvailable: (v) => `Version ${v} available`,
    verBeta: "Beta",
    verInstalled: (v) => `Installed: ${v}`,
    verPreShort: "pre-release",
    verPreToggle: "Show pre-releases",
    verPreToggleShort: "Also offer beta versions for testing. Applies to all users.",
    verPreHint:
      "HACS only installs pre-releases when \"Pre-release\" is switched on for this integration: enable and switch on the \"Pre-release\" entity on the HACS device.",
    verPreHintLink: "Open HACS device",
    verPreHintEnable:
      "HACS only installs pre-releases when \"Pre-release\" is switched on for this integration. The panel can do this for you: it enables the entity in HACS and switches it on. HACS briefly reloads (about 30 seconds). If you later switch \"Show pre-releases\" off, it is switched off again.",
    verPreEnable: "Enable in HACS",
    verPreEnabling: "Enabling … (up to 30 s)",
    verPreEnableError: "Enabling failed:",
    verPreEnableTimeout: "HACS did not provide the entity in time. Please check the HACS device.",
    verInstalledVia: (v, hacs) => `Installed: ${v}${hacs ? " · via HACS" : ""}`,
    verNoHacs: "Install via HACS or manually (see release notes).",
    verReleaseNotes: "Release notes",
    verUpdate: "Update",
    verInstalling: (v) => `Updating to ${v}…`,
    verInstallingSub: "HACS is downloading the new version",
    verInstallError: "Update failed:",
    verHacsSyncing: "Syncing with HACS …",
    verHacsPending:
      "HACS doesn't know this version yet. \"Check for updates\" makes HACS reload its versions; otherwise try again later.",
    verRestartNeeded: (v) => `${v} installed – restart required`,
    verRestartSub: "The new version only becomes active after restarting Home Assistant.",
    verRestart: "Restart now",
    verRestartConfirm: "Restart Home Assistant now? All integrations are briefly unavailable.",
    verRestarting: "Home Assistant is restarting…",
    availCtlNoData: "No data yet – recording started with the update to 2.9.0.",
    availRanges: { "24h": "24 h", "7d": "7 days", "30d": "30 days" },
    availRangeGroup: "Time range",
    availLoading: "Loading history…",
    loaderTitle: "Loader",
    loaderShort: "Animation shown while the history loads. Applies only to you, on all your devices.",
    settingsSaveHint: "\"Save\" applies to polling, automatic removal, notifications, updates and ping. Loader and connection take effect directly.",
    loaderNames: {
      elephant: ["Elephant", "Balancing on a ball"],
      cat: ["Cat", "Sneak and pounce"],
      hamster: ["Hamster", "In the wheel"],
      penguin: ["Penguin", "…and the polar bear"],
      runner: ["Runner bird", "…and the coyote"],
      random: ["Random", "A different one each time"],
    },
    loaderSelect: (name) => `Choose loader ${name}`,
    loaderWords: {
      cat: ["Sneaking up on the data…", "Wiggling. Any second…", "Pounce! Just missed.", "Acts like nothing happened."],
      hamster: ["Running as fast as he can…", "The wheel turns, the data comes.", "No break. No idea where to.", "Almost there…"],
      penguin: ["Waddling through the history…", "Someone's coming! Dive!", "The bear is still puzzled.", "Surfacing with the data…"],
      runner: ["Dashing through the history…", "The tunnel is only painted on. For some.", "Ouch.", "Mip mip! Data on its way…"],
    },
    availLoadingWords: [
      "Balancing through the history…",
      "Wobbles. Doesn't fall. Like the controller.",
      "An elephant never forgets, it just rolls slowly.",
      "Almost there…",
    ],
    availError: "History not available:",
    availNoEntity: "No online entity found - without a HA device there is no history.",
    availNoData: "No history data in the recorder for this time range.",
    availAlways: "Reachable the whole time",
    availNever: "Not reachable during the whole time range",
    availOutages: (n) => (n === 1 ? "1 outage" : `${n} outages`),
    availTotal: (d) => `${d} in total`,
    availLongest: (d) => `longest ${d}`,
    availSince: (time) => `data only since ${time}`,
    availOnline: "Reachable",
    availOffline: "Outage",
    availNone: "No data",
    availNow: "now",
    availOngoing: "ongoing",
    availMore: (n) => `${n} older outages not listed.`,
    availTip: "Offline",
    durMin: (n) => `${n} min`,
    durHour: (h, m) => (m ? `${h} h ${m} min` : `${h} h`),
    durDay: (d, h) => (h ? `${d} d ${h} h` : `${d} d`),
    quickProtect: "Protect",
    quickUnprotect: "Stop protecting",
    linkedNone: "No Home Assistant device linked.",
    linkAdd: "Link a device…",
    linkChange: "Change",
    linkRemove: "Remove link",
    linkCancel: "Cancel",
    linkOpen: (name) => `Open device page of ${name}`,
    pickerSearch: "Search devices (name, area, manufacturer)…",
    pickerSuggested: "Matches the MAC address",
    pickerAll: "All devices",
    pickerNone: "No device found.",
    pickerMore: (n) => `${n} more - refine the search.`,
    pickerCurrent: "linked",
    pickerHideLinked: "Hide already linked",
    pickerLinkedTo: (names) => `Already linked to: ${names}`,
    pickerHiddenCount: (n) =>
      n === 1 ? "1 already linked device hidden." : `${n} already linked devices hidden.`,
  },
};
